<div
  class="menu max-lg:bg-primary-900 top-0 left-0 z-10 flex flex-col max-lg:pointer-events-none max-lg:absolute max-lg:min-h-screen max-lg:w-full max-lg:-translate-y-full max-lg:p-5 max-lg:pt-20 max-lg:opacity-0 max-lg:transition-opacity lg:flex-row"
>
  <!-- prettier-ignore -->
  <?php foreach (Theme\Menu::items('main') as $item) { ?>
    <?= component('menu-item', ['item' => $item]); ?>
  <?php } ?>
</div>
