<?php
if (!$youtubeId) {
  return;
}

// Get thumbnail image URL
$image = "https://i.ytimg.com/vi/{$youtubeId}/maxresdefault.jpg";
$status = wp_remote_retrieve_response_code(wp_remote_get($image));

if ($status !== 200) {
  $image = "https://i.ytimg.com/vi/{$youtubeId}/hqdefault.jpg";
}
?>

<div class="aspect-video w-full overflow-hidden rounded bg-gray-600">
  <button
    aria-label="Play YouTube video"
    class="youtube group relative cursor-pointer"
    data-youtube-id="<?= $youtubeId; ?>"
  >
    <div
      class="bg-primary-600 group-hover:bg-primary-800 absolute top-1/2 left-1/2 flex aspect-square w-1/6 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full text-white transition-colors"
    >
      <svg
        class="h-1/3 w-1/3 translate-x-1/8"
        viewBox="0 0 40 40"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path
          d="m0 0 40 20-40 20z"
          fill="currentColor"
        />
      </svg>
    </div>

    <img
      src="<?= $image; ?>"
      width="720"
      height="<?= round((720 / 16) * 9); ?>"
      loading="lazy"
    />
  </button>
</div>
